### ISSUE TITLE
2.8.3: H5Vol w/o MPI Does not Compile with HDF5 1.14.0

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#3648]
**Describe the bug**
We are trying to use HDF5 1.14.0 in Conda-Forge with our latest release of ADIOS2, 2.8.3, but it fails to build.

**To Reproduce**
Compile ADIOS2 2.8.3 w/ HDF5 1.14.0 and w/o MPI as in https://github.com/conda-forge/adios2-feedstock/pull/70

This will fail with
```
In file included from /home/conda/feedstock_root/build_artifacts/adios2-split_1675744077213/work/source/h5vol/H5Vol.h:4,

                 from /home/conda/feedstock_root/build_artifacts/adios2-split_1675744077213/work/testing/h5vol/TestH5VolWriteReadBPFile.cpp:18:

/home/conda/feedstock_root/build_artifacts/adios2-split_1675744077213/work/source/h5vol/H5VolReadWrite.h:84:9: error: invalid conversion from 'herr_t (*)(void*, hid_t, hid_t, hid_t, hid_t, void*, void**)' {aka 'int (*)(void*, long int, long int, long int, long int, void*, void**)'} to 'herr_t (*)(size_t, void**, hid_t*, hid_t*, hid_t*, hid_t, void**, void**)' {aka 'int (*)(long unsigned int, void**, long int*, long int*, long int*, long int, void**, void**)'} [-fpermissive]

   84 |         H5VL_adios2_dataset_read, H5VL_adios2_dataset_write,

      |         ^~~~~~~~~~~~~~~~~~~~~~~~

      |         |

      |         herr_t (*)(void*, hid_t, hid_t, hid_t, hid_t, void*, void**) {aka int (*)(void*, long int, long int, long int, long int, void*, void**)}

/home/conda/feedstock_root/build_artifacts/adios2-split_1675744077213/work/source/h5vol/H5VolReadWrite.h:84:35: error: invalid conversion from 'herr_t (*)(void*, hid_t, hid_t, hid_t, hid_t, const void*, void**)' {aka 'int (*)(void*, long int, long int, long int, long int, const void*, void**)'} to 'herr_t (*)(size_t, void**, hid_t*, hid_t*, hid_t*, hid_t, const void**, void**)' {aka 'int (*)(long unsigned int, void**, long int*, long int*, long int*, long int, const void**, void**)'} [-fpermissive]

   84 |         H5VL_adios2_dataset_read, H5VL_adios2_dataset_write,

      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~

      |                                   |

      |                                   herr_t (*)(void*, hid_t, hid_t, hid_t, hid_t, const void*, void**) {aka int (*)(void*, long int, long int, long int, long int, const void*, void**)}

make[2]: *** [testing/h5vol/CMakeFiles/Test.Util.H5VOL.WriteReadBPFile.Serial.dir/build.make:79: testing/h5vol/CMakeFiles/Test.Util.H5VOL.WriteReadBPFile.Serial.dir/TestH5VolWriteReadBPFile.cpp.o] Error 1

*************************************************************************************************************

make[1]: *** [CMakeFiles/Makefile2:6373: testing/h5vol/CMakeFiles/Test.Util.H5VOL.WriteReadBPFile.Serial.dir/all] Error 2
```

**Expected behavior**
This should not fail to compile.

**Desktop (please complete the following information):**
 - OS/Platform: Ubuntu and macOS w/o MPI using HDF5 1.14.0
 - Build: for Linux, GCC 11.3.0 w/ the latest CMake

**Additional context**
cc @guj 

This blocks releasing an update to our software stack in conda-forge in https://github.com/conda-forge/adios2-feedstock/pull/70

**Comment by ax3l** [comment]
The H5Vol signatures changed in 1.14.0 according to @guj and were updated in ADIOS 2.9.0.

**Comment by ax3l** [comment]
I will disable H5Vol in ADIOS2 2.8.* with `-DADIOS2_HAVE_HDF5_VOL=OFF`

**Comment by pnorbert** [comment]
adios 2.8.x works with HDF5 1.12 Vol syntax, but unfortunately it only checks if HDF5 is version >= 1.12 so it builds with 1.14. To turn this off, run cmake with `-DADIOS2_HAVE_HDF5_VOL=OFF`
adios 2.9 works with HDF5 1.14 Vol syntax
