### ISSUE TITLE
ADIOS2: 2.9.0 MSVC w/ C-Blosc 2.9.0

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS2#3680]
ADIOS2 v2.9.0 does not compile with C-Blosc 2.9.0 on Windows:
```
...
    BPBackCompatBlosc.cpp
  C:\Program Files (x86)\blosc\include\blosc2.h(1056,5): error C7555: use of designated initializers requires at least '/std:c++20' [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\toolkit\format\bp\bpBackCompatOperation\compress\BPBackCompatBlosc.cpp(145,1): error C2589: '(': illegal token on right side of '::' [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\toolkit\format\bp\bpBackCompatOperation\compress\BPBackCompatBlosc.cpp(146): error C2062: type 'unknown-type' unexpected [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\toolkit\format\bp\bpBackCompatOperation\compress\BPBackCompatBlosc.cpp(146,1): error C2059: syntax error: ')' [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
```
and
```
...
    CompressBlosc.cpp
  C:\Program Files (x86)\blosc\include\blosc2.h(1056,5): error C7555: use of designated initializers requires at least '/std:c++20' [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\operator\compress\CompressBlosc.cpp(155,53): warning C4267: 'initializing': conversion from 'size_t' to 'int32_t', possible loss of data [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\operator\compress\CompressBlosc.cpp(177,36): warning C4267: 'argument': conversion from 'size_t' to 'int16_t', possible loss of data [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\operator\compress\CompressBlosc.cpp(184,1): error C2589: '(': illegal token on right side of '::' [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\operator\compress\CompressBlosc.cpp(185): error C2062: type 'unknown-type' unexpected [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\operator\compress\CompressBlosc.cpp(185,1): error C2059: syntax error: ')' [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\operator\compress\CompressBlosc.cpp(352,36): warning C4267: 'argument': conversion from 'size_t' to 'int16_t', possible loss of data [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\operator\compress\CompressBlosc.cpp(378,1): error C2589: '(': illegal token on right side of '::' [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\operator\compress\CompressBlosc.cpp(379): error C2062: type 'unknown-type' unexpected [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\operator\compress\CompressBlosc.cpp(379,1): error C2059: syntax error: ')' [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\operator\compress\CompressBlosc.cpp(427,32): warning C4267: 'argument': conversion from 'size_t' to 'int16_t', possible loss of data [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\operator\compress\CompressBlosc.cpp(429,61): warning C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
    CompressZFP.cpp
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\operator\compress\CompressZFP.cpp(192,47): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\operator\compress\CompressZFP.cpp(255,78): warning C4267: 'argument': conversion from 'size_t' to 'uint', possible loss of data [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\operator\compress\CompressZFP.cpp(260,43): warning C4267: 'argument': conversion from 'size_t' to 'uint', possible loss of data [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
  D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.9.0\source\adios2\operator\compress\CompressZFP.cpp(265,58): warning C4267: 'argument': conversion from 'size_t' to 'uint', possible loss of data [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
```

Compile toolchain details:
```
  -- Building for: Visual Studio 16 2019
  -- The C compiler identification is MSVC 19.29.30151.0
  -- The CXX compiler identification is MSVC 19.29.30151.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
...
    Features:
      Library Type: static (with PIC)
      Build Type:   Release
      Testing: OFF
      Examples: OFF
      Build Options:
        BP5       : OFF
        DataMan   : OFF
        DataSpaces: OFF
        HDF5      : OFF
        HDF5_VOL  : OFF
        MHS       : OFF
        SST       : OFF
        Fortran   : OFF
        MPI       : OFF
        Python    : OFF
        Blosc2    : ON
        BZip2     : OFF
        LIBPRESSIO: OFF
        MGARD     : OFF
        PNG       : OFF
        SZ        : OFF
        ZFP       : ON
        DAOS      : OFF
        IME       : OFF
        O_DIRECT  : OFF
        Sodium    : OFF
        Catalyst  : OFF
        SysVShMem : OFF
        UCX       : OFF
        ZeroMQ    : OFF
        Profiling : OFF
        Endian_Reverse: OFF
        AWSSDK    : OFF
        GPU_Support: OFF
        CUDA      : OFF
        Kokkos    : OFF
        Kokkos_CUDA: OFF
        Kokkos_HIP: OFF
      RDMA Transport for Staging: Unconfigured
  -- Configuring done (25.1s)
  -- Generating done (0.3s)
  -- Build files have been written to: D:/a/openPMD-api/openPMD-api/src/build-adios2
```

**Comment by ax3l** [comment]
X-ref: https://github.com/Blosc/c-blosc2/issues/526

**Comment by ax3l** [comment]
The other issue is:
- [Why is std::min failing when windows.h is included?](https://stackoverflow.com/questions/5004858/why-is-stdmin-failing-when-windows-h-is-included)

**Comment by ax3l** [comment]
Fixed uupstream in c-blosc2 and in ADIOS2 in the linked PRs :)
